//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMMaterial
    {
        public int ID { get; set; }
        public string Stock_Code { get; set; }
        public Nullable<decimal> UsedAmount { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public string MS_Code { get; set; }
        public string ENSave { get; set; }
        public Nullable<System.DateTime> DateSave { get; set; }
        public string BranchId { get; set; }
    }
}
