//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDoctor
    {
        public int ID { get; set; }
        public string DrID { get; set; }
        public string RoomID { get; set; }
        public Nullable<System.DateTime> DateBook { get; set; }
        public Nullable<System.DateTime> TimeStart { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string Duration { get; set; }
        public string Note { get; set; }
        public string BranchID { get; set; }
        public string ENSave { get; set; }
        public Nullable<System.DateTime> DateSave { get; set; }
        public Nullable<int> IDBookLink { get; set; }
    }
}
