//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionRate
    {
        public int ID { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Com_Rate { get; set; }
        public string EN_Save { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
    }
}
