//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactCustomer
    {
        public int Id { get; set; }
        public string CN { get; set; }
        public string PrefixCode { get; set; }
        public string Tname { get; set; }
        public string TsurName { get; set; }
        public string TNickname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string SurName { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string RelationFlag { get; set; }
        public string RelationOther { get; set; }
    }
}
