//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public string CD_Code { get; set; }
        public string BankName { get; set; }
        public string CashTyp { get; set; }
        public Nullable<int> ShowOrder { get; set; }
        public string BankFullName { get; set; }
        public string NoBill { get; set; }
        public string CardType { get; set; }
        public string BillType { get; set; }
        public string Showed { get; set; }
    }
}
