//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerConnect
    {
        public int ID { get; set; }
        public string ContactName { get; set; }
        public string ContactFrom { get; set; }
        public string Mobile { get; set; }
        public string ContactFB_IN_LineID { get; set; }
        public string Interest { get; set; }
        public Nullable<System.DateTime> DateConnect { get; set; }
        public Nullable<System.DateTime> DateBooking { get; set; }
        public Nullable<decimal> CloseBal { get; set; }
        public string Remark { get; set; }
        public string EN_Consult { get; set; }
        public Nullable<System.DateTime> DateSave { get; set; }
        public string EN_Save { get; set; }
        public string BookBranchId { get; set; }
    }
}
