//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string CN { get; set; }
        public Nullable<System.DateTime> Dateregister { get; set; }
        public string PrefixCode { get; set; }
        public string Tname { get; set; }
        public string TsurName { get; set; }
        public string Tnickname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string DateBirthOther { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weights { get; set; }
        public string Nationality { get; set; }
        public string Race { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string E_mail { get; set; }
        public string AddressId { get; set; }
        public string Building { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string Sub_districtCode { get; set; }
        public string DistrictCode { get; set; }
        public string ProvinceCode { get; set; }
        public string Postcode { get; set; }
        public string PassportNo { get; set; }
        public string IdCard { get; set; }
        public string VipFlag { get; set; }
        public string Remark { get; set; }
        public string AllergyHistory { get; set; }
        public string UnderlyingDisease { get; set; }
        public string WhereGotTreatment { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Image { get; set; }
        public string CustomerType { get; set; }
        public string CN_old { get; set; }
        public string BranchID { get; set; }
        public string AgenMemID { get; set; }
        public string BloodPressure { get; set; }
        public string ProviderTypID { get; set; }
        public Nullable<int> Credit_Bath { get; set; }
        public Nullable<int> Credit_Day { get; set; }
        public string Country_ID { get; set; }
        public string SaleConsult { get; set; }
        public string MainOfficeCust { get; set; }
        public string BranchCust { get; set; }
        public string Celeb { get; set; }
        public string BranchAuth { get; set; }
    }
}
