//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProvider
    {
        public string ProviderTypID { get; set; }
        public string ProviderTypName { get; set; }
        public Nullable<int> ORD { get; set; }
        public string ShowWith { get; set; }
    }
}
