//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public int ID { get; set; }
        public string District_CODE { get; set; }
        public string District_NAME { get; set; }
        public Nullable<int> PROVINCE_CODE { get; set; }
    }
}
