//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftVoucher
    {
        public string GiftCode { get; set; }
        public Nullable<decimal> PriceCredit { get; set; }
        public string GiftDetail { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Gift_Active { get; set; }
        public int ID { get; set; }
        public string CN { get; set; }
        public string EN { get; set; }
        public string Remark { get; set; }
        public string MS_Code { get; set; }
        public string ListOrder { get; set; }
        public string Sono { get; set; }
        public string MS_CodeFIX { get; set; }
        public string ENApp { get; set; }
        public string GiftType { get; set; }
    }
}
