//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HowYouhear
    {
        public int ID { get; set; }
        public string CN { get; set; }
        public string Newspaper { get; set; }
        public string Magazine { get; set; }
        public string Internet { get; set; }
        public string Friend { get; set; }
        public string Travelthrough { get; set; }
        public string HowYouhearOther { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Sms { get; set; }
        public string LineAt { get; set; }
        public string Line { get; set; }
        public string Taxi { get; set; }
        public string Agency { get; set; }
    }
}
