//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTran
    {
        public int ID { get; set; }
        public string SONo { get; set; }
        public string INVNo { get; set; }
        public Nullable<System.DateTime> INVDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<decimal> INVBath { get; set; }
        public string Vat { get; set; }
        public string BranchId { get; set; }
    }
}
