//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOrderMoveTran
    {
        public string SOClose { get; set; }
        public string SONew { get; set; }
        public string MS_Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string IsCancel { get; set; }
    }
}
