//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalStuff
    {
        public string VN { get; set; }
        public string MS_Code { get; set; }
        public string Position_ID { get; set; }
        public string EmployeeId { get; set; }
        public string UseTransId { get; set; }
        public string SUR_ID { get; set; }
        public Nullable<decimal> Com_Bath { get; set; }
        public Nullable<System.DateTime> Com_Date { get; set; }
        public string EN_Save { get; set; }
        public string SectionStuff { get; set; }
        public string MergStatus { get; set; }
        public string ListOrder { get; set; }
    }
}
