//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOrderFileScanCustomer
    {
        public int Id { get; set; }
        public string UseTransId { get; set; }
        public string FileName { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DateScan { get; set; }
        public string Sono { get; set; }
        public string VN { get; set; }
        public string CN { get; set; }
        public string ENDoctor { get; set; }
        public string ENSave { get; set; }
    }
}
