//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOrderMove
    {
        public string SOClose { get; set; }
        public string SONew { get; set; }
        public string CN { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public Nullable<decimal> PriceNewVN { get; set; }
        public Nullable<decimal> PriceNewBalance { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> PayCash { get; set; }
        public Nullable<bool> PayUse { get; set; }
    }
}
