//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCardsTran
    {
        public int ID { get; set; }
        public string MemID { get; set; }
        public string ScanBy { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
    }
}
