//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALabel
    {
        public string MS_Code { get; set; }
        public string Amount { get; set; }
        public string Perday { get; set; }
        public string BeforeMeals { get; set; }
        public string Morning { get; set; }
        public string Lunch { get; set; }
        public string Evening { get; set; }
        public string BeforeBed { get; set; }
        public string Everyhours { get; set; }
        public string ENSave { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string AfterMeals { get; set; }
        public string eat { get; set; }
        public string coat { get; set; }
        public string coatArea { get; set; }
    }
}
