//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayByItem
    {
        public int ID { get; set; }
        public string VN { get; set; }
        public string SOno { get; set; }
        public string MS_Code { get; set; }
        public string ListOrder { get; set; }
        public Nullable<decimal> CashMoney { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string PayRefID { get; set; }
        public Nullable<decimal> MoneyCredit { get; set; }
    }
}
