//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayInCome
    {
        public int PayInID { get; set; }
        public string PayInName { get; set; }
        public string PayInTyp { get; set; }
        public string BankNumber { get; set; }
        public string BankFullName { get; set; }
        public string NoBill { get; set; }
    }
}
