//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int ID { get; set; }
        public string AddressId { get; set; }
        public string Building { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<System.DateTime> DateEndW { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<System.DateTime> DateStartW { get; set; }
        public string DistrictCode { get; set; }
        public string EFirstname { get; set; }
        public string ELastname { get; set; }
        public string EMiddlename { get; set; }
        public string EN { get; set; }
        public string ENickname { get; set; }
        public string E_mail { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Height { get; set; }
        public string IdCard { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Nationality { get; set; }
        public string PassportId { get; set; }
        public string Passwords { get; set; }
        public string PersonnelType { get; set; }
        public string PostCode { get; set; }
        public string ProvinceCode { get; set; }
        public string Race { get; set; }
        public string Road { get; set; }
        public string Soi { get; set; }
        public string Sub_districtCode { get; set; }
        public string TName { get; set; }
        public string TNickname { get; set; }
        public string TSurname { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string UpdateBy { get; set; }
        public string UserGroup { get; set; }
        public Nullable<int> Weights { get; set; }
        public string Username { get; set; }
        public string PrefixCode { get; set; }
        public string ImageFilename { get; set; }
        public string BranchID { get; set; }
        public string Active { get; set; }
        public string BranchAuth { get; set; }
    }
}
