//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundMoneyType
    {
        public string MoneyID { get; set; }
        public string MoneyText { get; set; }
        public Nullable<short> Ord { get; set; }
        public string Active { get; set; }
    }
}
