//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBookDoctor
    {
        public string RoomIDDocBook { get; set; }
        public string RoomName { get; set; }
        public string RoomDetail { get; set; }
        public Nullable<int> ShowOrder { get; set; }
        public string Show { get; set; }
        public string RoomIDBooking { get; set; }
        public Nullable<int> AddDate { get; set; }
    }
}
