//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOClose
    {
        public int ID { get; set; }
        public string VN { get; set; }
        public string SOno { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<System.DateTime> RefundDate { get; set; }
        public string RefundType { get; set; }
        public string RefundRemark { get; set; }
        public string SaveBy { get; set; }
    }
}
