//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockREQTran
    {
        public string REQNo { get; set; }
        public string MS_Code { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> QuantityReply { get; set; }
        public string REQUnitCode { get; set; }
        public Nullable<decimal> QuantityReceive { get; set; }
    }
}
