//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSPQ
    {
        public string SPQNo { get; set; }
        public Nullable<System.DateTime> REQDate { get; set; }
        public string EN_Req { get; set; }
        public string EN_ReqTo { get; set; }
        public string Remark { get; set; }
        public string Req_BranchId { get; set; }
        public string ReqTo_BranchId { get; set; }
        public int Id { get; set; }
        public string RemarkReply { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> Replydate { get; set; }
        public string WHCode { get; set; }
        public string Dept { get; set; }
        public string REPNo { get; set; }
        public string ReturnsFlag { get; set; }
        public string UrgentFlag { get; set; }
        public string Fortype { get; set; }
        public string SOno { get; set; }
    }
}
