//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplieTransRenewal
    {
        public string SONo { get; set; }
        public string VN { get; set; }
        public string MS_Code { get; set; }
        public string ListOrder { get; set; }
        public string EN { get; set; }
        public Nullable<System.DateTime> SaveDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RenewStartDate { get; set; }
    }
}
