//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxTran
    {
        public int ID { get; set; }
        public string SONo { get; set; }
        public string TaxNo { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<decimal> TaxBath { get; set; }
        public string BranchId { get; set; }
    }
}
