//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryuwatWebApplication.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Customer
    {
        public string CN { get; set; }
        public Nullable<System.DateTime> Dateregister { get; set; }
        public string PrefixName { get; set; }
        public Nullable<int> PrefixCode { get; set; }
        public string Tname { get; set; }
        public string TsurName { get; set; }
        public string Nickname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weights { get; set; }
        public string Nationality { get; set; }
        public string Race { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string E_mail { get; set; }
        public string AddressId { get; set; }
        public string Building { get; set; }
        public string Soi { get; set; }
        public string Road { get; set; }
        public string Sub_districtCode { get; set; }
        public string SUBDISTRICT_NAME { get; set; }
        public string DistrictCode { get; set; }
        public string District_NAME { get; set; }
        public string ProvinceCode { get; set; }
        public string PROVINCE_NAME { get; set; }
        public string zipcode { get; set; }
        public string PassportID { get; set; }
        public string Emercontact { get; set; }
        public string EmerRelationship { get; set; }
        public Nullable<System.DateTime> DateStartW { get; set; }
        public Nullable<System.DateTime> DateEndW { get; set; }
        public string Passwords { get; set; }
        public string UserGroup { get; set; }
    }
}
